#!/usr/bin/env python3
"""Plan validation and deliberate publication without network or credential access."""
import json
from datetime import datetime, timezone
import os
from pathlib import Path
import re
import subprocess

RELEASE = re.compile(r"v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)")
SHA = re.compile(r"[0-9a-f]{40}")
LABEL = re.compile(r"[a-z0-9]+(?:-[a-z0-9]+)*")


def obligations(paths):
    """Unknown/shared inputs select both domains; only packaging selects images."""
    backend = frontend = python = image = False
    for path in paths:
        if path.startswith("docs/") or path in (
                "README.md", "CONTRIBUTING.md", "AGENTS.md", "REVIEW.md", "LICENSE",
                "docker/production/README.md", "docker/build/x86_64/README.md",
                "ui/v2.5/README.md", "ui/v2.5/src/locales/README.md",
                "pkg/sqlite/migrations/README.md", "pkg/plugin/examples/README.md",
                "pkg/plugin/examples/react-component/README.md"):
            continue
        if path in ("Makefile", ".dockerignore", "scripts/check_intel_runtime.py") or path.startswith("docker/"):
            backend = frontend = image = True
        elif path.startswith("scripts/") and path.endswith(".py"):
            python = True
        elif path.startswith("ui/v2.5/"):
            frontend = True
            # Login locales are also embedded/generated by the backend.
            backend |= path.startswith("ui/v2.5/src/locales/")
        elif path.startswith(("cmd/", "internal/", "pkg/")) or path in ("go.mod", "go.sum") or (
                "/" not in path and path.endswith(".go")):
            backend = True
        else:
            # Schema, generators, workflow, root configuration, and new paths.
            backend = frontend = python = True
    return {"backend": backend, "frontend": frontend, "python": python, "build_image": image}


def affected(paths):
    groups = obligations(paths)
    return any(groups[key] for key in ("backend", "frontend", "python")), groups["build_image"]


def plan(event_name, ref_type, ref_name, sha, repository, event, paths=(), run_id="1", attempt="1"):
    if not SHA.fullmatch(sha) or not re.fullmatch(r"[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+", repository):
        raise ValueError("invalid source identity")
    local = "vexxx-ci:" + sha
    result = {"run_tests": False, "backend": False, "frontend": False, "python": False,
              "deferred": False, "build_image": False, "publish": False,
              "local_ref": local, "image_ref": "", "sha_ref": "", "latest_ref": "", "version": "ci-" + sha[:12]}
    if event.get("deleted"):
        return result
    if event_name == "push" and ref_type == "tag":
        # The workflow glob is only a prefilter. This is the exact version gate.
        if not RELEASE.fullmatch(ref_name) or len(ref_name) > 128:
            raise ValueError("release must be exact vMAJOR.MINOR.PATCH without leading zeros or suffixes")
        image = "ghcr.io/" + repository.lower()
        result.update(run_tests=True, backend=True, frontend=True, python=True, build_image=True, publish=True,
                      image_ref=image + ":" + ref_name, sha_ref=image + ":sha-" + sha, version=ref_name)
    elif event_name == "workflow_dispatch":
        result.update(run_tests=True, backend=True, frontend=True, python=True, build_image=True)
        inputs = event.get("inputs") or {}
        publish = inputs.get("publish_test_image", "false")
        latest = inputs.get("publish_latest", "false")
        for key, value in (("publish_test_image", publish), ("publish_latest", latest)):
            if not (isinstance(value, bool) or isinstance(value, str) and value in ("true", "false")):
                raise ValueError(key + " must be boolean")
        publish = publish is True or publish == "true"
        latest = latest is True or latest == "true"
        if publish and latest:
            raise ValueError("choose test publication or latest publication, not both")
        if publish or latest:
            if ref_type != "branch" or ref_name != "master":
                raise ValueError("publication requires the controlled master ref")
            label = inputs.get("test_label", "")
            if not isinstance(label, str) or not 1 <= len(label) <= 32 or not LABEL.fullmatch(label):
                raise ValueError("test_label must be 1..32 lowercase letters/digits with single internal hyphens")
            if not re.fullmatch(r"[1-9][0-9]{0,19}", run_id) or not re.fullmatch(r"[1-9][0-9]{0,5}", attempt):
                raise ValueError("invalid workflow run identity")
            tag = f"{'candidate' if latest else 'test'}-{label}-{run_id}-{attempt}"
            package = "ghcr.io/" + repository.lower() + ("" if latest else "-test")
            result.update(publish=True, image_ref=package + ":" + tag, version=tag,
                          latest_ref=package + ":latest" if latest else "")
    elif event_name == "pull_request" or (event_name == "push" and ref_type == "branch" and ref_name == "master"):
        groups = obligations(paths)
        result.update(groups, run_tests=any(groups[key] for key in ("backend", "frontend", "python")))
        if event_name == "pull_request" and event.get("pull_request", {}).get("draft"):
            result.update(deferred=True, run_tests=False, backend=False, frontend=False,
                          python=False, build_image=False)
    else:
        raise ValueError("unsupported publication event")
    return result


def changed_paths(event_name, event, cwd, checkout=None):
    if event_name == "pull_request":
        pr = event["pull_request"]
        base, head = pr["base"]["sha"], pr["head"]["sha"]
    elif event_name == "push":
        base, head = event["before"], event["after"]
    else:
        return []
    if not SHA.fullmatch(base) or not SHA.fullmatch(head):
        raise ValueError("invalid diff identity")
    if base == "0" * 40:
        command = ["git", "ls-tree", "-r", "--name-only", "-z", head]
    else:
        if event_name == "pull_request":
            base = subprocess.check_output(["git", "merge-base", base, head], cwd=cwd, timeout=60).decode().strip()
            if not SHA.fullmatch(base):
                raise ValueError("invalid merge base")
        # No rename folding: both deleted and added paths influence classification.
        command = ["git", "diff", "--no-renames", "--name-only", "-z", base, head]
    paths = [os.fsdecode(p) for p in subprocess.check_output(command, cwd=cwd, timeout=60).split(b"\0") if p]
    if event_name == "pull_request" and checkout is not None:
        # Base changes introduced by the merge tree also select confirmation.
        paths.extend(os.fsdecode(p) for p in subprocess.check_output(
            ["git", "diff", "--no-renames", "--name-only", "-z", head, checkout],
            cwd=cwd, timeout=60).split(b"\0") if p)
    return paths


def checkout_identity(cwd, expected):
    if not SHA.fullmatch(expected):
        raise ValueError("invalid checkout identity")
    actual = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=cwd, timeout=60).decode().strip()
    tree = subprocess.check_output(["git", "rev-parse", "HEAD^{tree}"], cwd=cwd, timeout=60).decode().strip()
    if actual != expected or not SHA.fullmatch(tree):
        raise ValueError("checkout does not match the event revision")
    return tree


def main():
    event = json.loads(Path(os.environ["GITHUB_EVENT_PATH"]).read_text())
    name, kind = os.environ["GITHUB_EVENT_NAME"], os.environ["GITHUB_REF_TYPE"]
    sha = os.environ["GITHUB_SHA"]
    tree = checkout_identity(Path.cwd(), sha)
    if name == "pull_request" and event["pull_request"]["merge_commit_sha"] != sha:
        raise ValueError("checkout is not the expected PR merge revision")
    if name == "push" and kind == "branch" and not event.get("deleted") and event["after"] != sha:
        raise ValueError("checkout is not the landed revision")
    if name == "push" and kind == "tag" and not event.get("deleted"):
        subprocess.run(["git", "merge-base", "--is-ancestor", sha, "refs/remotes/origin/master"],
                       check=True, cwd=Path.cwd(), timeout=60)
    paths = changed_paths(name, event, Path.cwd(), sha) if (
        name == "pull_request" or (name == "push" and kind == "branch" and not event.get("deleted"))) else []
    result = plan(name, kind, os.environ["GITHUB_REF_NAME"], os.environ["GITHUB_SHA"],
                  os.environ["GITHUB_REPOSITORY"], event, paths,
                  os.environ.get("GITHUB_RUN_ID", "1"), os.environ.get("GITHUB_RUN_ATTEMPT", "1"))
    timestamp = subprocess.check_output(["git", "show", "-s", "--format=%ct", sha], timeout=60).decode().strip()
    build_date = datetime.fromtimestamp(int(timestamp), timezone.utc).strftime("%Y-%m-%d %H:%M:%S")
    result.update(checkout=sha, tree=tree, build_date=build_date)
    if name == "pull_request":
        pr = event["pull_request"]
        result.update(base=pr["base"]["sha"], head=pr["head"]["sha"])
        result["merge_base"] = subprocess.check_output(
            ["git", "merge-base", result["base"], result["head"]], timeout=60).decode().strip()
    elif name == "push":
        result.update(base=event.get("before", ""), head=event.get("after", sha))
    print(json.dumps(result, sort_keys=True))
    if os.environ.get("GITHUB_STEP_SUMMARY"):
        with Path(os.environ["GITHUB_STEP_SUMMARY"]).open("a") as summary:
            summary.write("### Validation plan\n\n```json\n" + json.dumps(result, sort_keys=True, indent=2) + "\n```\n")
    with Path(os.environ["GITHUB_OUTPUT"]).open("a") as output:
        for key, value in result.items():
            output.write(f"{key}={str(value).lower() if isinstance(value, bool) else value}\n")


if __name__ == "__main__":
    main()
